name: Bioinformatics Programming & Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/AppData/Local/pip/Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path .\requirements.txt) { pip install -r .\requirements.txt }

      - name: Cache R dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.r') }}
          restore-keys: |
            ${{ runner.os }}-r-
        if: runner.os == 'Windows'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - name: Run Project
        run: |
         if (Test-Path .\run_project.bat) { .\run_project.bat }
         else { Write-Host "run_project.bat not found!" }

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-output-artifact
          path: output/
