name: Bioinformatics Programming & Stats

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Cache R dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.r') }}
          restore-keys: |
            ${{ runner.os }}-r-
        if: runner.os == 'Linux'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - name: Run Project
        run: |
          if [ -f run_project.sh ]; then
            chmod +x run_project.sh
            ./run_project.sh
          else
            echo "run_project.sh not found!"
          fi

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-output-artifact
          path: output/
