name: Bioinformatics Programming & Stats

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.1.1"

      - name: Install dependencies
        run: |
          sudo apt-get install -y libxml2-dev # Add any additional dependencies here
          Rscript -e 'install.packages(c("remotes", "rcmdcheck"))'

      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'

      - name: Install R packages from install_r.r
        run: RScript install_r_library.r

      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main Python script
        run: |
          python main_script.py

      - name: Run R scripts
        run: |
          RScript ./src/part_3_graphs.R
          RScript ./src/part_4_5.r

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-output-artifact
          path: output/
