name: Bioinformatics Programming & Stats

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3
      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.10"
      
      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Run main Python script
      #   run: |
      #     python main_script.py

      # - name: Create artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-output-artifact
      #     path: output/
      
      # Load repo and install R
    
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
  
      # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("rvest")'
