name: R Workflow

on:
  push:
    branches:
      - main

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0' # You can specify the version you need

    # - name: Install dependencies
    #   run: Rscript -e 'install.packages("your_package")' # Replace "your_package" with the actual package name

    - name: Run R script
      run: echo 'print("Hello, world!")' | R --vanilla
