name: R Workflow

on:
  push:
    branches:
      - main

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.3.1' # You can specify the version you need

    - name: Run R script
      run: |
        echo 'print("Hello, world!")'

    # - name: Run R script
    #   run: Rscript path/to/your/script.R
