name: R Workflow

on:
  push:
    branches:
      - main

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0' # You can try using a different version that might be available

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base

    - name: Run R script
      run: |
        echo 'print("Hello, world!")' | R --vanilla

    # - name: Run R script
    #   run: Rscript path/to/your/script.R
